using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace nilnul.obj_.deV.as_
{
	/// <summary>
	/// grow knowledge. <see cref="nilnul._obj.typ._id.IInfoGrow"/>
	/// </summary>
	/// <remarks>
	/// especailly so in AI age when current stock of knowledge can be generated by AI, leaving human representing newly found knowledge in code;
	/// </remarks>
	internal class IKnowledge
	{
	}
}
