//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.dev.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection srcs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["srcs"]));
            }
            set {
                this["srcs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".nilnulCfg")]
        public string folder_srcCfg_doc {
            get {
                return ((string)(this["folder_srcCfg_doc"]));
            }
            set {
                this["folder_srcCfg_doc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("my")]
        public string src_destination_my {
            get {
                return ((string)(this["src_destination_my"]));
            }
            set {
                this["src_destination_my"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pub")]
        public string src_destination_pub {
            get {
                return ((string)(this["src_destination_pub"]));
            }
            set {
                this["src_destination_pub"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("src_")]
        public string src_destination {
            get {
                return ((string)(this["src_destination"]));
            }
            set {
                this["src_destination"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nilnul")]
        public string src_destination_nilnul {
            get {
                return ((string)(this["src_destination_nilnul"]));
            }
            set {
                this["src_destination_nilnul"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string srcsParent {
            get {
                return ((string)(this["srcsParent"]));
            }
            set {
                this["srcsParent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("src_")]
        public string divisionInPersonal4srcsParent {
            get {
                return ((string)(this["divisionInPersonal4srcsParent"]));
            }
            set {
                this["divisionInPersonal4srcsParent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string my_address {
            get {
                return ((string)(this["my_address"]));
            }
            set {
                this["my_address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string my_division_in_personal {
            get {
                return ((string)(this["my_division_in_personal"]));
            }
            set {
                this["my_division_in_personal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tgt_address {
            get {
                return ((string)(this["tgt_address"]));
            }
            set {
                this["tgt_address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_tgt_")]
        public string tgt_division_in_my {
            get {
                return ((string)(this["tgt_division_in_my"]));
            }
            set {
                this["tgt_division_in_my"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool upgraded {
            get {
                return ((bool)(this["upgraded"]));
            }
            set {
                this["upgraded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_dev_/_nuget_/_src_")]
        public string nugetPacsSrc_division {
            get {
                return ((string)(this["nugetPacsSrc_division"]));
            }
            set {
                this["nugetPacsSrc_division"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>_my_</string>
  <string>_pub_</string>
  <string>_nilnul_</string>
  <string>_team1_</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection srcDirS {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["srcDirS"]));
            }
            set {
                this["srcDirS"] = value;
            }
        }
    }
}
