//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.dev.src.prj_.db._meta_.evt_.build_._post {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nilnul.dev.src.prj_.db._meta_.evt_.build_._post.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setlocal
        ///		@rem		set date0=%date%
        ///		@rem %date% is susceptible to regional format settintings
        ///
        ///for /F &quot;usebackq tokens=1,2 delims==&quot; %%i in (`wmic os get LocalDateTime /VALUE 2^&gt;NUL`) do if &apos;.%%i.&apos;==&apos;.LocalDateTime.&apos; set ldt=%%j
        ///set ldt=%ldt:~0,4%-%ldt:~4,2%-%ldt:~6,2% %ldt:~8,2%:%ldt:~10,2%:%ldt:~12,6%
        ///echo Local date is [%ldt%]
        ///
        ///		set date0=%ldt%
        ///
        ///		set	year=%date0:~2,2%
        ///		set	month=%date0:~5,2%
        ///		set 	day=%date0:~8,2%
        ///		echo year month day: %year% %month% %day%
        ///
        ///@rem The 3rd number is the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nugetPostBuild_bat {
            get {
                return ResourceManager.GetString("nugetPostBuild.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if $(ConfigurationName) == Release (
        ///    pushd  &quot;$(ProjectDir)&quot;
        ///    &quot;$(ProjectDir)nugetPostbuild.bat&quot;
        ///    popd
        ///).
        /// </summary>
        internal static string postBuildEvent {
            get {
                return ResourceManager.GetString("postBuildEvent", resourceCulture);
            }
        }
    }
}
