using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace nilnul.fs.folder.dirs_
{
	/// <summary>
	/// remove VisualStudio autogenerated ones, which are not source code, but derived compiled code; 
	/// </summary>
	internal class IUnVsGen
	{
	}
}
