using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace nilnul.dev.prj_.person_.my.data
{
	/// <summary>
	/// eg:
	///		a document is smeared to cover sensitive info. Even the document is generated by the original one, but per the perspective of information, the generated one is included, and hence depended on by, the original one. So the generated one can be put back in the public personal prj(<see cref="dev.sln_._person.Li_.Full"/>), which is a precursor to personal prj that is based on public proj.
	///		, So data generation, and information inclusion have opposite direction of "precedent/subsequent" relation;
	/// </summary>
    class IRegress
    {
    }
}
